namespace CryptoTxt.Security
{
    // <auto-generated>
    // Este arquivo é reescrito pelo Build-Exe.ps1 produzindo a chave pública da assinatura
    // do executável em builds de distribuição (PublishSingleFile). Em builds de dev
    // (dotnet build/publish) permanece o stub abaixo (HasToken = false) e o IntegrityGuard
    // usa o modo de auto-pin em LocalAppData.
    internal static class IntegrityToken
    {
        public const string ModulusBase64 = "";
        public const string ExponentBase64 = "";

        public static bool HasToken => ModulusBase64.Length > 0 && ExponentBase64.Length > 0;
    }
}